canal:
  server: 192.168.0.80:11111
  destination: example
spring:
  application:
    name: canal-example
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fencheng_core
    username: root
    password: 123456
  jooq:
    sql-dialect: mysql
  flyway:
    baseline-on-migrate: true